# fly.toml app configuration file generated for shlyapa-telegram-bot on 2025-08-08T10:36:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shlyapa-telegram-bot'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
